project:
  name: LLM Augmented Knowledge Graph Based Recommender System
  base_dir: /home/kchauhan/repos/mds-tmu-mrp/
  data_dir: /home/kchauhan/repos/mds-tmu-mrp/datasets

amazon_reviews_dataset:
  category: 'Books' # 'Books', 'Electronics', 'Movies_and_TV', 'Video_Games'

duckdb:
  database: '/home/kchauhan/repos/mds-tmu-mrp/db/duckdb/amazon_reviews.duckdb'
  review_table: raw_review_Books
  meta_table: raw_meta_Books
  
neo4j:
  uri: 'bolt://localhost:7687'
  user: 'neo4j'
  password: 'tmu-2024'




